### ISSUE TITLE
Thinner covers from SWF to MP4

### ISSUE THREAD

**Issue by uppsddn** [Phlow/netlabels.org#1]
Hola,

Did you remember Thinner Netlabel in-motion covers? I used to collect them and found some Flash files still working. I am converting those SWF files in HD MP4 videos (720x720 or 1080x1080). According to each animation, videos length are from 30 seconds to 7.5 minutes (15.5 MB for the 7 minutes one)

Let me know if you want to replace the THN cover images for those squared videos. `video width="390" height="390" autoplay loop` is working great :-) YouTube embed isn't working well because resize the videos with a huge black container.

And muchas gracias for Netlabels.org project :-)

**Comment by uppsddn** [comment]
Sorry, forgot to include the link above [THN060 on YouTube](https://www.youtube.com/watch?v=u211LXZzxPI)

**Comment by Phlow** [comment]
hello @uppsddn I just saw your message. That's a great idea. I don't know if I have the time to do it right now, but please send me the videos and I include them :)

this is my email

![bildschirmfoto 2018-11-09 um 14 44 40](https://user-images.githubusercontent.com/2551270/48265898-119e0f80-e42e-11e8-8ed9-415dbaa3056a.png)

**Comment by Phlow** [comment]
@uppsddn The best way is https://wetransfer.com/ in my opinion…

**Comment by uppsddn** [comment]
Sure, I will.

I have been uploading some of those SWF to YouTube but how the squaring
code isn't always working, I'm also cutting the videos into 720x720 px

They are on my desktop, so I'll send it to you via WeTransfer when I'm back
to Colombia in mid-December. Right now I'm in Berlín in case you live here
and have an extra computer free for two or three hours, I can do some

Thanks for answering and keeping projects like this alive 😊

**Comment by Phlow** [comment]
@uppsddn Thankyou very much :) Currently I rebuild my old http://phlow-magazine.com to work again on smartphones ;)
